float64 phi_measured            # the adjusted measured double-difference phase-range
geometry_msgs/Vector3 r_1a_a    # vector to first satellite at time a
geometry_msgs/Vector3 r_1a_b    # vector to first satellite at time b
geometry_msgs/Vector3 r_2a_a    # vector to second satellite at time a
geometry_msgs/Vector3 r_2a_b    # vector to second satellite at time b
uint8 prn1                      # satellite ID number of first satellite
uint8 prn2                      # satellite ID number of second satellite
